insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('1','Trà sữa trân châu','Trà sữa','30000.0','Trà sữa vị truyền thống với trân châu đen','src/ass/b1.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('2','Matcha Latte','Cà phê','45000.0','Latte trà xanh Nhật Bản','src/ass/b2.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('3','Cà phê sữa đá','Cà phê','25000.0','Cà phê sữa đá Việt Nam','src/ass/b3.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('4','Mocha Frappuccino','Cà phê','50000.0','Cà phê đá xay Mocha','src/ass/b4.png','8');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('5','Kem dâu tây','Kem','35000.0','Kem dâu tươi mát','src/ass/b5.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('6','Sinh tố bơ','Sinh tố','40000.0','Sinh tố bơ ngậy béo','src/ass/b6.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('7','Coconut Milkshake','Sinh tố','42000.0','Sữa dừa đá xay','src/ass/b7.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('8','Trà đào cam sả','Trà','32000.0','Trà đào với hương cam sả tươi','src/ass/b8.png','9');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('9','Caramel Macchiato','Cà phê','55000.0','Macchiato caramel đậm đà','src/ass/b9.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('10','Nước mía','Giải khát','15000.0','Nước mía nguyên chất','src/ass/b10.png','10');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('11','Trà vải hoa hồng','Trà','35000.0','Trà vải kèm hoa hồng thơm nhẹ','src/ass/b11.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('12','Bubblegum Smoothie','Sinh tố','45000.0','Sinh tố kẹo cao su','src/ass/b12.png','2');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('13','Espresso','Cà phê','30000.0','Cà phê Espresso nguyên chất','src/ass/b13.png','8');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('14','Cà phê đen đá','Cà phê','20000.0','Cà phê đen đậm vị','src/ass/b14.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('15','Mango Tango','Sinh tố','42000.0','Sinh tố xoài kết hợp đào','src/ass/b15.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('16','Affogato','Kem','50000.0','Kem vani với espresso nóng','src/ass/b16.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('17','Strawberry Cheesecake Shake','Sinh tố','55000.0','Sinh tố bánh cheesecake dâu','src/ass/b17.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('18','Bạc xỉu','Cà phê','28000.0','Cà phê sữa đặc nhẹ vị','src/ass/b18.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('19','Pina Colada','Sinh tố','48000.0','Sinh tố dứa và cốt dừa','src/ass/b19.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('20','Blue Lagoon','Giải khát','50000.0','Nước chanh soda màu xanh','src/ass/b20.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('21','Trà xanh sữa','Trà sữa','38000.0','Trà xanh matcha với sữa','src/ass/b21.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('22','Thai Tea','Trà sữa','40000.0','Trà sữa Thái màu cam đặc trưng','src/ass/b22.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('23','Dalgona Coffee','Cà phê','45000.0','Cà phê Dalgona bông xốp','src/ass/b23.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('24','Orange Sunset','Giải khát','47000.0','Nước cam pha với grenadine','src/ass/b24.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('25','Chocolate Shake','Sinh tố','38000.0','Sinh tố socola nguyên chất','src/ass/b25.png','8');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('26','Lychee Mojito','Giải khát','52000.0','Mojito vải bạc hà','src/ass/b26.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('27','Sinh tố dâu','Sinh tố','35000.0','Sinh tố dâu tươi','src/ass/b27.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('28','Americano','Cà phê','28000.0','Cà phê Americano nhẹ vị','src/ass/b28.png','9');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('29','Oreo Milkshake','Sinh tố','46000.0','Sinh tố bánh Oreo','src/ass/b29.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('30','Trà atiso','Trà','30000.0','Trà atiso thanh mát','src/ass/b30.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('31','Passion Fruit Tea','Trà','32000.0','Trà chanh leo thơm ngon','src/ass/b31.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('32','Dark Chocolate Mocha','Cà phê','55000.0','Mocha socola đắng','src/ass/b32.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('33','Sinh tố mít','Sinh tố','37000.0','Sinh tố mít thơm ngọt','src/ass/b33.png','8');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('34','Vietnamese Egg Coffee','Cà phê','45000.0','Cà phê trứng Hà Nội','src/ass/b34.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('35','Cookies & Cream Shake','Sinh tố','50000.0','Sinh tố bánh quy kem','src/ass/b35.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('36','Bubblegum Soda','Giải khát','48000.0','Soda hương kẹo cao su','src/ass/b36.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('37','Chanh tuyết','Giải khát','32000.0','Nước chanh đá xay','src/ass/b37.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('38','Peach Tea','Trà','35000.0','Trà đào mật ong','src/ass/b38.png','8');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('39','Black Sesame Latte','Cà phê','52000.0','Latte mè đen Nhật Bản','src/ass/b39.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('40','Sinh tố xoài','Sinh tố','38000.0','Sinh tố xoài chín','src/ass/b40.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('41','Cà phê Cappuccino','Cà phê','50000.0','Cappuccino nguyên bản','src/ass/b41.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('42','Sinh tố mãng cầu','Sinh tố','40000.0','Sinh tố mãng cầu ngọt','src/ass/b42.png','7');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('43','Jasmine Milk Tea','Trà sữa','42000.0','Trà sữa hoa nhài thơm nhẹ','src/ass/b43.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('44','Kem bạc hà sô cô la','Kem','45000.0','Kem vị bạc hà mix socola','src/ass/b44.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('45','Cam vắt','Giải khát','30000.0','Nước cam tươi nguyên chất','src/ass/b45.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('46','Sinh tố táo','Sinh tố','35000.0','Sinh tố táo xanh','src/ass/b46.png','6');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('47','Nước sả gừng','Giải khát','28000.0','Nước sả gừng ấm bụng','src/ass/b47.png','4');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('48','Mango Matcha Latte','Cà phê','55000.0','Latte matcha kết hợp xoài','src/ass/b48.png','3');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('49','Soda việt quất','Giải khát','48000.0','Soda hương việt quất','src/ass/b49.png','5');
insert into `tb_Mon`(`idMon`,`tenMon`,`loaiMon`,`giaMon`,`ghiChu`,`hinhAnh`,`soLuong`) values('50','Sinh tố chanh dây','Sinh tố','35000.0','Sinh tố chanh dây tươi','src/ass/b50.png','7');
